# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x07kvstore\">\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x14\n\x0coperation_id\x18\x03 \x01(\t\"/\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0coperation_id\x18\x02 \x01(\t\">\n\x0bGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"2\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0coperation_id\x18\x02 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0bListRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\">\n\x0cListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x0c\x43learRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\"1\n\rClearResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9c\x02\n\x0eKVStoreService\x12\x30\n\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x12\x30\n\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12\x39\n\x06\x44\x65lete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse\x12\x33\n\x04List\x12\x14.kvstore.ListRequest\x1a\x15.kvstore.ListResponse\x12\x36\n\x05\x43lear\x12\x15.kvstore.ClearRequest\x1a\x16.kvstore.ClearResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=26
  _globals['_PUTREQUEST']._serialized_end=88
  _globals['_PUTRESPONSE']._serialized_start=90
  _globals['_PUTRESPONSE']._serialized_end=137
  _globals['_GETREQUEST']._serialized_start=139
  _globals['_GETREQUEST']._serialized_end=186
  _globals['_GETRESPONSE']._serialized_start=188
  _globals['_GETRESPONSE']._serialized_end=250
  _globals['_DELETEREQUEST']._serialized_start=252
  _globals['_DELETEREQUEST']._serialized_end=302
  _globals['_DELETERESPONSE']._serialized_start=304
  _globals['_DELETERESPONSE']._serialized_end=354
  _globals['_LISTREQUEST']._serialized_start=356
  _globals['_LISTREQUEST']._serialized_end=391
  _globals['_LISTRESPONSE']._serialized_start=393
  _globals['_LISTRESPONSE']._serialized_end=455
  _globals['_CLEARREQUEST']._serialized_start=457
  _globals['_CLEARREQUEST']._serialized_end=493
  _globals['_CLEARRESPONSE']._serialized_start=495
  _globals['_CLEARRESPONSE']._serialized_end=544
  _globals['_KVSTORESERVICE']._serialized_start=547
  _globals['_KVSTORESERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)